//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xameteo.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Application {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Application() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xameteo.Resx.Application", typeof(Application).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonrise.
        /// </summary>
        internal static string ASTRO_MOONRISE {
            get {
                return ResourceManager.GetString("ASTRO_MOONRISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moonset.
        /// </summary>
        internal static string ASTRO_MOONSET {
            get {
                return ResourceManager.GetString("ASTRO_MOONSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        internal static string ASTRO_SUNRISE {
            get {
                return ResourceManager.GetString("ASTRO_SUNRISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        internal static string ASTRO_SUNSET {
            get {
                return ResourceManager.GetString("ASTRO_SUNSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here!.
        /// </summary>
        internal static string BUTTON_DEFAULT {
            get {
                return ResourceManager.GetString("BUTTON_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CONDITION_1000 {
            get {
                return ResourceManager.GetString("CONDITION_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly Cloudy.
        /// </summary>
        internal static string CONDITION_1003 {
            get {
                return ResourceManager.GetString("CONDITION_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        internal static string CONDITION_1006 {
            get {
                return ResourceManager.GetString("CONDITION_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string CONDITION_1009 {
            get {
                return ResourceManager.GetString("CONDITION_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string CONDITION_1030 {
            get {
                return ResourceManager.GetString("CONDITION_1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy rain nearby.
        /// </summary>
        internal static string CONDITION_1063 {
            get {
                return ResourceManager.GetString("CONDITION_1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy snow nearby.
        /// </summary>
        internal static string CONDITION_1066 {
            get {
                return ResourceManager.GetString("CONDITION_1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy sleet nearby.
        /// </summary>
        internal static string CONDITION_1069 {
            get {
                return ResourceManager.GetString("CONDITION_1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy freezing drizzle nearby.
        /// </summary>
        internal static string CONDITION_1072 {
            get {
                return ResourceManager.GetString("CONDITION_1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thundery outbreaks in nearby.
        /// </summary>
        internal static string CONDITION_1087 {
            get {
                return ResourceManager.GetString("CONDITION_1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing snow.
        /// </summary>
        internal static string CONDITION_1114 {
            get {
                return ResourceManager.GetString("CONDITION_1114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        internal static string CONDITION_1117 {
            get {
                return ResourceManager.GetString("CONDITION_1117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string CONDITION_1135 {
            get {
                return ResourceManager.GetString("CONDITION_1135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing fog.
        /// </summary>
        internal static string CONDITION_1147 {
            get {
                return ResourceManager.GetString("CONDITION_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light drizzle.
        /// </summary>
        internal static string CONDITION_1150 {
            get {
                return ResourceManager.GetString("CONDITION_1150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light drizzle.
        /// </summary>
        internal static string CONDITION_1153 {
            get {
                return ResourceManager.GetString("CONDITION_1153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        internal static string CONDITION_1168 {
            get {
                return ResourceManager.GetString("CONDITION_1168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy freezing drizzle.
        /// </summary>
        internal static string CONDITION_1171 {
            get {
                return ResourceManager.GetString("CONDITION_1171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain.
        /// </summary>
        internal static string CONDITION_1180 {
            get {
                return ResourceManager.GetString("CONDITION_1180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain.
        /// </summary>
        internal static string CONDITION_1183 {
            get {
                return ResourceManager.GetString("CONDITION_1183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate rain at times.
        /// </summary>
        internal static string CONDITION_1186 {
            get {
                return ResourceManager.GetString("CONDITION_1186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate rain.
        /// </summary>
        internal static string CONDITION_1189 {
            get {
                return ResourceManager.GetString("CONDITION_1189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain at times.
        /// </summary>
        internal static string CONDITION_1192 {
            get {
                return ResourceManager.GetString("CONDITION_1192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain.
        /// </summary>
        internal static string CONDITION_1195 {
            get {
                return ResourceManager.GetString("CONDITION_1195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light freezing rain.
        /// </summary>
        internal static string CONDITION_1198 {
            get {
                return ResourceManager.GetString("CONDITION_1198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy freezing rain.
        /// </summary>
        internal static string CONDITION_1201 {
            get {
                return ResourceManager.GetString("CONDITION_1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light sleet.
        /// </summary>
        internal static string CONDITION_1204 {
            get {
                return ResourceManager.GetString("CONDITION_1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet.
        /// </summary>
        internal static string CONDITION_1207 {
            get {
                return ResourceManager.GetString("CONDITION_1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow.
        /// </summary>
        internal static string CONDITION_1210 {
            get {
                return ResourceManager.GetString("CONDITION_1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light snow.
        /// </summary>
        internal static string CONDITION_1213 {
            get {
                return ResourceManager.GetString("CONDITION_1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy moderate snow.
        /// </summary>
        internal static string CONDITION_1216 {
            get {
                return ResourceManager.GetString("CONDITION_1216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate snow.
        /// </summary>
        internal static string CONDITION_1219 {
            get {
                return ResourceManager.GetString("CONDITION_1219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy heavy snow.
        /// </summary>
        internal static string CONDITION_1222 {
            get {
                return ResourceManager.GetString("CONDITION_1222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy snow.
        /// </summary>
        internal static string CONDITION_1225 {
            get {
                return ResourceManager.GetString("CONDITION_1225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice pellets.
        /// </summary>
        internal static string CONDITION_1237 {
            get {
                return ResourceManager.GetString("CONDITION_1237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain shower.
        /// </summary>
        internal static string CONDITION_1240 {
            get {
                return ResourceManager.GetString("CONDITION_1240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain shower.
        /// </summary>
        internal static string CONDITION_1243 {
            get {
                return ResourceManager.GetString("CONDITION_1243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrential rain shower.
        /// </summary>
        internal static string CONDITION_1246 {
            get {
                return ResourceManager.GetString("CONDITION_1246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light sleet showers.
        /// </summary>
        internal static string CONDITION_1249 {
            get {
                return ResourceManager.GetString("CONDITION_1249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet showers.
        /// </summary>
        internal static string CONDITION_1252 {
            get {
                return ResourceManager.GetString("CONDITION_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light snow showers.
        /// </summary>
        internal static string CONDITION_1255 {
            get {
                return ResourceManager.GetString("CONDITION_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow showers.
        /// </summary>
        internal static string CONDITION_1258 {
            get {
                return ResourceManager.GetString("CONDITION_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light showers of ice pellets.
        /// </summary>
        internal static string CONDITION_1261 {
            get {
                return ResourceManager.GetString("CONDITION_1261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy showers of ice pellets.
        /// </summary>
        internal static string CONDITION_1264 {
            get {
                return ResourceManager.GetString("CONDITION_1264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain in area with thunder.
        /// </summary>
        internal static string CONDITION_1273 {
            get {
                return ResourceManager.GetString("CONDITION_1273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain in area with thunder.
        /// </summary>
        internal static string CONDITION_1276 {
            get {
                return ResourceManager.GetString("CONDITION_1276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow in area with thunder.
        /// </summary>
        internal static string CONDITION_1279 {
            get {
                return ResourceManager.GetString("CONDITION_1279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow in area with thunder.
        /// </summary>
        internal static string CONDITION_1282 {
            get {
                return ResourceManager.GetString("CONDITION_1282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud coverage.
        /// </summary>
        internal static string FORECAST_CLOUD {
            get {
                return ResourceManager.GetString("FORECAST_CLOUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string FORECAST_CONDITION {
            get {
                return ResourceManager.GetString("FORECAST_CONDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        internal static string FORECAST_FEELS_LIKE {
            get {
                return ResourceManager.GetString("FORECAST_FEELS_LIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string FORECAST_HUMIDITY {
            get {
                return ResourceManager.GetString("FORECAST_HUMIDITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime.
        /// </summary>
        internal static string FORECAST_IS_DAY {
            get {
                return ResourceManager.GetString("FORECAST_IS_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string FORECAST_LAST_UPDATED {
            get {
                return ResourceManager.GetString("FORECAST_LAST_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        internal static string FORECAST_PRECIPITATION {
            get {
                return ResourceManager.GetString("FORECAST_PRECIPITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string FORECAST_PRESSURE {
            get {
                return ResourceManager.GetString("FORECAST_PRESSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string FORECAST_TEMPERATURE {
            get {
                return ResourceManager.GetString("FORECAST_TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string FORECAST_VISIBILITY {
            get {
                return ResourceManager.GetString("FORECAST_VISIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind degree.
        /// </summary>
        internal static string FORECAST_WIND_DEGREE {
            get {
                return ResourceManager.GetString("FORECAST_WIND_DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind direction.
        /// </summary>
        internal static string FORECAST_WIND_DIRECTION {
            get {
                return ResourceManager.GetString("FORECAST_WIND_DIRECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind velocity.
        /// </summary>
        internal static string FORECAST_WIND_VELOCITY {
            get {
                return ResourceManager.GetString("FORECAST_WIND_VELOCITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string LOCATION_COUNTRY {
            get {
                return ResourceManager.GetString("LOCATION_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string LOCATION_LATITUDE {
            get {
                return ResourceManager.GetString("LOCATION_LATITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local time.
        /// </summary>
        internal static string LOCATION_LOCAL_TIME {
            get {
                return ResourceManager.GetString("LOCATION_LOCAL_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string LOCATION_LONGITUDE {
            get {
                return ResourceManager.GetString("LOCATION_LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LOCATION_NAME {
            get {
                return ResourceManager.GetString("LOCATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string LOCATION_REGION {
            get {
                return ResourceManager.GetString("LOCATION_REGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string LOCATION_TIMEZONE {
            get {
                return ResourceManager.GetString("LOCATION_TIMEZONE", resourceCulture);
            }
        }
    }
}
