//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xameteo.Resx
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xameteo.Resx.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Faro Airport.
        /// </summary>
        internal static string Airport_FAO
        {
            get
            {
                return ResourceManager.GetString("Airport_FAO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cristiano Ronaldo International Airport, Funchal.
        /// </summary>
        internal static string Airport_FNC
        {
            get
            {
                return ResourceManager.GetString("Airport_FNC", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Horta Airport.
        /// </summary>
        internal static string Airport_HOR
        {
            get
            {
                return ResourceManager.GetString("Airport_HOR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Humberto Delgado Airport, Lisbon.
        /// </summary>
        internal static string Airport_LIS
        {
            get
            {
                return ResourceManager.GetString("Airport_LIS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Francisco Sá Carneiro Airport, Porto.
        /// </summary>
        internal static string Airport_OPO
        {
            get
            {
                return ResourceManager.GetString("Airport_OPO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to João Paulo II Airport, Ponta Delgada.
        /// </summary>
        internal static string Airport_PDL
        {
            get
            {
                return ResourceManager.GetString("Airport_PDL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Porto Santo Airport.
        /// </summary>
        internal static string Airport_PXO
        {
            get
            {
                return ResourceManager.GetString("Airport_PXO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Santa Maria Airport.
        /// </summary>
        internal static string Airport_SMA
        {
            get
            {
                return ResourceManager.GetString("Airport_SMA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lajes Field, Terceira.
        /// </summary>
        internal static string Airport_TER
        {
            get
            {
                return ResourceManager.GetString("Airport_TER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moonrise.
        /// </summary>
        internal static string Astro_Moonrise
        {
            get
            {
                return ResourceManager.GetString("Astro_Moonrise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moonset.
        /// </summary>
        internal static string Astro_Moonset
        {
            get
            {
                return ResourceManager.GetString("Astro_Moonset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        internal static string Astro_Sunrise
        {
            get
            {
                return ResourceManager.GetString("Astro_Sunrise", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        internal static string Astro_Sunset
        {
            get
            {
                return ResourceManager.GetString("Astro_Sunset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel
        {
            get
            {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click here!.
        /// </summary>
        internal static string Button_Default
        {
            get
            {
                return ResourceManager.GetString("Button_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK
        {
            get
            {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string Compass_E
        {
            get
            {
                return ResourceManager.GetString("Compass_E", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to East-northeast.
        /// </summary>
        internal static string Compass_ENE
        {
            get
            {
                return ResourceManager.GetString("Compass_ENE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to East-southeast.
        /// </summary>
        internal static string Compass_ESE
        {
            get
            {
                return ResourceManager.GetString("Compass_ESE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string Compass_N
        {
            get
            {
                return ResourceManager.GetString("Compass_N", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Northeast.
        /// </summary>
        internal static string Compass_NE
        {
            get
            {
                return ResourceManager.GetString("Compass_NE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to North-northeast.
        /// </summary>
        internal static string Compass_NNE
        {
            get
            {
                return ResourceManager.GetString("Compass_NNE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to North-northwest.
        /// </summary>
        internal static string Compass_NNW
        {
            get
            {
                return ResourceManager.GetString("Compass_NNW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Northwest.
        /// </summary>
        internal static string Compass_NW
        {
            get
            {
                return ResourceManager.GetString("Compass_NW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        internal static string Compass_S
        {
            get
            {
                return ResourceManager.GetString("Compass_S", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Southeast.
        /// </summary>
        internal static string Compass_SE
        {
            get
            {
                return ResourceManager.GetString("Compass_SE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to South-southeast.
        /// </summary>
        internal static string Compass_SSE
        {
            get
            {
                return ResourceManager.GetString("Compass_SSE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to South-southwest.
        /// </summary>
        internal static string Compass_SSW
        {
            get
            {
                return ResourceManager.GetString("Compass_SSW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Southwest.
        /// </summary>
        internal static string Compass_SW
        {
            get
            {
                return ResourceManager.GetString("Compass_SW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string Compass_W
        {
            get
            {
                return ResourceManager.GetString("Compass_W", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to West-northwest.
        /// </summary>
        internal static string Compass_WNW
        {
            get
            {
                return ResourceManager.GetString("Compass_WNW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to West-southwest.
        /// </summary>
        internal static string Compass_WSW
        {
            get
            {
                return ResourceManager.GetString("Compass_WSW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Condition_1000
        {
            get
            {
                return ResourceManager.GetString("Condition_1000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Partly Cloudy.
        /// </summary>
        internal static string Condition_1003
        {
            get
            {
                return ResourceManager.GetString("Condition_1003", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        internal static string Condition_1006
        {
            get
            {
                return ResourceManager.GetString("Condition_1006", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string Condition_1009
        {
            get
            {
                return ResourceManager.GetString("Condition_1009", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string Condition_1030
        {
            get
            {
                return ResourceManager.GetString("Condition_1030", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy rain nearby.
        /// </summary>
        internal static string Condition_1063
        {
            get
            {
                return ResourceManager.GetString("Condition_1063", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy snow nearby.
        /// </summary>
        internal static string Condition_1066
        {
            get
            {
                return ResourceManager.GetString("Condition_1066", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy sleet nearby.
        /// </summary>
        internal static string Condition_1069
        {
            get
            {
                return ResourceManager.GetString("Condition_1069", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy freezing drizzle nearby.
        /// </summary>
        internal static string Condition_1072
        {
            get
            {
                return ResourceManager.GetString("Condition_1072", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thundery outbreaks in nearby.
        /// </summary>
        internal static string Condition_1087
        {
            get
            {
                return ResourceManager.GetString("Condition_1087", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blowing snow.
        /// </summary>
        internal static string Condition_1114
        {
            get
            {
                return ResourceManager.GetString("Condition_1114", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        internal static string Condition_1117
        {
            get
            {
                return ResourceManager.GetString("Condition_1117", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string Condition_1135
        {
            get
            {
                return ResourceManager.GetString("Condition_1135", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freezing fog.
        /// </summary>
        internal static string Condition_1147
        {
            get
            {
                return ResourceManager.GetString("Condition_1147", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy light drizzle.
        /// </summary>
        internal static string Condition_1150
        {
            get
            {
                return ResourceManager.GetString("Condition_1150", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light drizzle.
        /// </summary>
        internal static string Condition_1153
        {
            get
            {
                return ResourceManager.GetString("Condition_1153", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        internal static string Condition_1168
        {
            get
            {
                return ResourceManager.GetString("Condition_1168", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heavy freezing drizzle.
        /// </summary>
        internal static string Condition_1171
        {
            get
            {
                return ResourceManager.GetString("Condition_1171", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain.
        /// </summary>
        internal static string Condition_1180
        {
            get
            {
                return ResourceManager.GetString("Condition_1180", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light rain.
        /// </summary>
        internal static string Condition_1183
        {
            get
            {
                return ResourceManager.GetString("Condition_1183", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate rain at times.
        /// </summary>
        internal static string Condition_1185
        {
            get
            {
                return ResourceManager.GetString("Condition_1185", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate rain.
        /// </summary>
        internal static string Condition_1189
        {
            get
            {
                return ResourceManager.GetString("Condition_1189", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heavy rain at times.
        /// </summary>
        internal static string Condition_1192
        {
            get
            {
                return ResourceManager.GetString("Condition_1192", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heavy rain.
        /// </summary>
        internal static string Condition_1195
        {
            get
            {
                return ResourceManager.GetString("Condition_1195", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light freezing rain.
        /// </summary>
        internal static string Condition_1198
        {
            get
            {
                return ResourceManager.GetString("Condition_1198", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy freezing rain.
        /// </summary>
        internal static string Condition_1201
        {
            get
            {
                return ResourceManager.GetString("Condition_1201", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light sleet.
        /// </summary>
        internal static string Condition_1204
        {
            get
            {
                return ResourceManager.GetString("Condition_1204", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet.
        /// </summary>
        internal static string Condition_1207
        {
            get
            {
                return ResourceManager.GetString("Condition_1207", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow.
        /// </summary>
        internal static string Condition_1210
        {
            get
            {
                return ResourceManager.GetString("Condition_1210", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light snow.
        /// </summary>
        internal static string Condition_1213
        {
            get
            {
                return ResourceManager.GetString("Condition_1213", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy moderate snow.
        /// </summary>
        internal static string Condition_1216
        {
            get
            {
                return ResourceManager.GetString("Condition_1216", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate snow.
        /// </summary>
        internal static string Condition_1219
        {
            get
            {
                return ResourceManager.GetString("Condition_1219", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy heavy snow.
        /// </summary>
        internal static string Condition_1222
        {
            get
            {
                return ResourceManager.GetString("Condition_1222", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heavy snow.
        /// </summary>
        internal static string Condition_1225
        {
            get
            {
                return ResourceManager.GetString("Condition_1225", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ice pellets.
        /// </summary>
        internal static string Condition_1237
        {
            get
            {
                return ResourceManager.GetString("Condition_1237", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light rain shower.
        /// </summary>
        internal static string Condition_1240
        {
            get
            {
                return ResourceManager.GetString("Condition_1240", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain shower.
        /// </summary>
        internal static string Condition_1243
        {
            get
            {
                return ResourceManager.GetString("Condition_1243", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torrential rain shower.
        /// </summary>
        internal static string Condition_1246
        {
            get
            {
                return ResourceManager.GetString("Condition_1246", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light sleet showers.
        /// </summary>
        internal static string Condition_1249
        {
            get
            {
                return ResourceManager.GetString("Condition_1249", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet showers.
        /// </summary>
        internal static string Condition_1252
        {
            get
            {
                return ResourceManager.GetString("Condition_1252", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light snow showers.
        /// </summary>
        internal static string Condition_1255
        {
            get
            {
                return ResourceManager.GetString("Condition_1255", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow showers.
        /// </summary>
        internal static string Condition_1258
        {
            get
            {
                return ResourceManager.GetString("Condition_1258", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light showers of ice pellets.
        /// </summary>
        internal static string Condition_1261
        {
            get
            {
                return ResourceManager.GetString("Condition_1261", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy showers of ice pellets.
        /// </summary>
        internal static string Condition_1264
        {
            get
            {
                return ResourceManager.GetString("Condition_1264", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain in area with thunder.
        /// </summary>
        internal static string Condition_1273
        {
            get
            {
                return ResourceManager.GetString("Condition_1273", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain in area with thunder.
        /// </summary>
        internal static string Condition_1276
        {
            get
            {
                return ResourceManager.GetString("Condition_1276", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow in area with thunder.
        /// </summary>
        internal static string Condition_1279
        {
            get
            {
                return ResourceManager.GetString("Condition_1279", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow in area with thunder.
        /// </summary>
        internal static string Condition_1282
        {
            get
            {
                return ResourceManager.GetString("Condition_1282", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cloud coverage.
        /// </summary>
        internal static string Forecast_Cloud
        {
            get
            {
                return ResourceManager.GetString("Forecast_Cloud", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Forecast_Condition
        {
            get
            {
                return ResourceManager.GetString("Forecast_Condition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Feels Like.
        /// </summary>
        internal static string Forecast_Feels_Like
        {
            get
            {
                return ResourceManager.GetString("Forecast_Feels_Like", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Forecast_Humidity
        {
            get
            {
                return ResourceManager.GetString("Forecast_Humidity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Daytime.
        /// </summary>
        internal static string Forecast_Is_Day
        {
            get
            {
                return ResourceManager.GetString("Forecast_Is_Day", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last updated.
        /// </summary>
        internal static string Forecast_Last_Updated
        {
            get
            {
                return ResourceManager.GetString("Forecast_Last_Updated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        internal static string Forecast_Precipitation
        {
            get
            {
                return ResourceManager.GetString("Forecast_Precipitation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Forecast_Pressure
        {
            get
            {
                return ResourceManager.GetString("Forecast_Pressure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Forecast_Temperature
        {
            get
            {
                return ResourceManager.GetString("Forecast_Temperature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Forecast_Visibility
        {
            get
            {
                return ResourceManager.GetString("Forecast_Visibility", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wind degree.
        /// </summary>
        internal static string Forecast_Wind_Degree
        {
            get
            {
                return ResourceManager.GetString("Forecast_Wind_Degree", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wind direction.
        /// </summary>
        internal static string Forecast_Wind_Direction
        {
            get
            {
                return ResourceManager.GetString("Forecast_Wind_Direction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wind velocity.
        /// </summary>
        internal static string Forecast_Wind_Velocity
        {
            get
            {
                return ResourceManager.GetString("Forecast_Wind_Velocity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The remote server returned an unexpected response &quot;{0}&quot;, expected &quot;OK&quot;....
        /// </summary>
        internal static string Geolocation_Error
        {
            get
            {
                return ResourceManager.GetString("Geolocation_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter your address and/or city on the input box below..
        /// </summary>
        internal static string Geolocation_Message
        {
            get
            {
                return ResourceManager.GetString("Geolocation_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple locations found.
        /// </summary>
        internal static string Geolocation_Multiple
        {
            get
            {
                return ResourceManager.GetString("Geolocation_Multiple", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geolocation.
        /// </summary>
        internal static string Geolocation_Title
        {
            get
            {
                return ResourceManager.GetString("Geolocation_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geolocation query returned zero results!.
        /// </summary>
        internal static string Geolocation_Zero
        {
            get
            {
                return ResourceManager.GetString("Geolocation_Zero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No
        {
            get
            {
                return ResourceManager.GetString("Global_No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes
        {
            get
            {
                return ResourceManager.GetString("Global_Yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Group_Distance
        {
            get
            {
                return ResourceManager.GetString("Group_Distance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        internal static string Group_Precipitation
        {
            get
            {
                return ResourceManager.GetString("Group_Precipitation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        internal static string Group_Pressure
        {
            get
            {
                return ResourceManager.GetString("Group_Pressure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Group_Temperature
        {
            get
            {
                return ResourceManager.GetString("Group_Temperature", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        internal static string Group_Velocity
        {
            get
            {
                return ResourceManager.GetString("Group_Velocity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string Loading_Title
        {
            get
            {
                return ResourceManager.GetString("Loading_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Location_Country
        {
            get
            {
                return ResourceManager.GetString("Location_Country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Location_Latitude
        {
            get
            {
                return ResourceManager.GetString("Location_Latitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local time.
        /// </summary>
        internal static string Location_Local_Time
        {
            get
            {
                return ResourceManager.GetString("Location_Local_Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Location_Longitude
        {
            get
            {
                return ResourceManager.GetString("Location_Longitude", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Location_Name
        {
            get
            {
                return ResourceManager.GetString("Location_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Location_Region
        {
            get
            {
                return ResourceManager.GetString("Location_Region", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string Location_Timezone
        {
            get
            {
                return ResourceManager.GetString("Location_Timezone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an airport.
        /// </summary>
        internal static string Prompt_Airport
        {
            get
            {
                return ResourceManager.GetString("Prompt_Airport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose location source.
        /// </summary>
        internal static string Prompt_Source
        {
            get
            {
                return ResourceManager.GetString("Prompt_Source", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove &quot;{0}&quot; from your locations?.
        /// </summary>
        internal static string Remove_Message
        {
            get
            {
                return ResourceManager.GetString("Remove_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove location.
        /// </summary>
        internal static string Remove_Title
        {
            get
            {
                return ResourceManager.GetString("Remove_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apixu Key.
        /// </summary>
        internal static string Settings_ApixuKey
        {
            get
            {
                return ResourceManager.GetString("Settings_ApixuKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geocoding Key.
        /// </summary>
        internal static string Settings_GoogleKey
        {
            get
            {
                return ResourceManager.GetString("Settings_GoogleKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} units.
        /// </summary>
        internal static string Settings_Units
        {
            get
            {
                return ResourceManager.GetString("Settings_Units", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Airports.
        /// </summary>
        internal static string Source_Airport
        {
            get
            {
                return ResourceManager.GetString("Source_Airport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string Source_Device
        {
            get
            {
                return ResourceManager.GetString("Source_Device", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Geolocation.
        /// </summary>
        internal static string Source_Geolocation
        {
            get
            {
                return ResourceManager.GetString("Source_Geolocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to atm.
        /// </summary>
        internal static string Symbol_Atmosphere
        {
            get
            {
                return ResourceManager.GetString("Symbol_Atmosphere", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string Symbol_Celsius
        {
            get
            {
                return ResourceManager.GetString("Symbol_Celsius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string Symbol_Centimeters
        {
            get
            {
                return ResourceManager.GetString("Symbol_Centimeters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to deg.
        /// </summary>
        internal static string Symbol_Degrees
        {
            get
            {
                return ResourceManager.GetString("Symbol_Degrees", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string Symbol_E
        {
            get
            {
                return ResourceManager.GetString("Symbol_E", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ENE.
        /// </summary>
        internal static string Symbol_ENE
        {
            get
            {
                return ResourceManager.GetString("Symbol_ENE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ESE.
        /// </summary>
        internal static string Symbol_ESE
        {
            get
            {
                return ResourceManager.GetString("Symbol_ESE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to °F.
        /// </summary>
        internal static string Symbol_Fahrenheit
        {
            get
            {
                return ResourceManager.GetString("Symbol_Fahrenheit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string Symbol_Inches
        {
            get
            {
                return ResourceManager.GetString("Symbol_Inches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string Symbol_Kelvin
        {
            get
            {
                return ResourceManager.GetString("Symbol_Kelvin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string Symbol_Kilometers
        {
            get
            {
                return ResourceManager.GetString("Symbol_Kilometers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kph.
        /// </summary>
        internal static string Symbol_Kilometers_Hour
        {
            get
            {
                return ResourceManager.GetString("Symbol_Kilometers_Hour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to kPa.
        /// </summary>
        internal static string Symbol_Kilopascal
        {
            get
            {
                return ResourceManager.GetString("Symbol_Kilopascal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        internal static string Symbol_Knots
        {
            get
            {
                return ResourceManager.GetString("Symbol_Knots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string Symbol_Meters
        {
            get
            {
                return ResourceManager.GetString("Symbol_Meters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        internal static string Symbol_Meters_Second
        {
            get
            {
                return ResourceManager.GetString("Symbol_Meters_Second", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string Symbol_Miles
        {
            get
            {
                return ResourceManager.GetString("Symbol_Miles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string Symbol_Miles_Hour
        {
            get
            {
                return ResourceManager.GetString("Symbol_Miles_Hour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mb.
        /// </summary>
        internal static string Symbol_Millibars
        {
            get
            {
                return ResourceManager.GetString("Symbol_Millibars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string Symbol_Millimeters
        {
            get
            {
                return ResourceManager.GetString("Symbol_Millimeters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Symbol_N
        {
            get
            {
                return ResourceManager.GetString("Symbol_N", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string Symbol_NE
        {
            get
            {
                return ResourceManager.GetString("Symbol_NE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NNE.
        /// </summary>
        internal static string Symbol_NNE
        {
            get
            {
                return ResourceManager.GetString("Symbol_NNE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        internal static string Symbol_NNW
        {
            get
            {
                return ResourceManager.GetString("Symbol_NNW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        internal static string Symbol_NW
        {
            get
            {
                return ResourceManager.GetString("Symbol_NW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Symbol_S
        {
            get
            {
                return ResourceManager.GetString("Symbol_S", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string Symbol_SE
        {
            get
            {
                return ResourceManager.GetString("Symbol_SE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SSE.
        /// </summary>
        internal static string Symbol_SSE
        {
            get
            {
                return ResourceManager.GetString("Symbol_SSE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        internal static string Symbol_SSW
        {
            get
            {
                return ResourceManager.GetString("Symbol_SSW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string Symbol_SW
        {
            get
            {
                return ResourceManager.GetString("Symbol_SW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to torr.
        /// </summary>
        internal static string Symbol_Torr
        {
            get
            {
                return ResourceManager.GetString("Symbol_Torr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Symbol_W
        {
            get
            {
                return ResourceManager.GetString("Symbol_W", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        internal static string Symbol_WNW
        {
            get
            {
                return ResourceManager.GetString("Symbol_WNW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        internal static string Symbol_WSW
        {
            get
            {
                return ResourceManager.GetString("Symbol_WSW", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forecast.
        /// </summary>
        internal static string Tab_Forecast
        {
            get
            {
                return ResourceManager.GetString("Tab_Forecast", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HIstory.
        /// </summary>
        internal static string Tab_History
        {
            get
            {
                return ResourceManager.GetString("Tab_History", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Tab_Now
        {
            get
            {
                return ResourceManager.GetString("Tab_Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Tab_Today
        {
            get
            {
                return ResourceManager.GetString("Tab_Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Locations.
        /// </summary>
        internal static string Title_Locations
        {
            get
            {
                return ResourceManager.GetString("Title_Locations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Title_Preferences
        {
            get
            {
                return ResourceManager.GetString("Title_Preferences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atmosphere.
        /// </summary>
        internal static string Units_Atmosphere
        {
            get
            {
                return ResourceManager.GetString("Units_Atmosphere", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Celsius.
        /// </summary>
        internal static string Units_Celsius
        {
            get
            {
                return ResourceManager.GetString("Units_Celsius", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        internal static string Units_Centimeters
        {
            get
            {
                return ResourceManager.GetString("Units_Centimeters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fahrenheit.
        /// </summary>
        internal static string Units_Fahrenheit
        {
            get
            {
                return ResourceManager.GetString("Units_Fahrenheit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Units_Inches
        {
            get
            {
                return ResourceManager.GetString("Units_Inches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kelvin.
        /// </summary>
        internal static string Units_Kelvin
        {
            get
            {
                return ResourceManager.GetString("Units_Kelvin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        internal static string Units_Kilometers
        {
            get
            {
                return ResourceManager.GetString("Units_Kilometers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kilometers per hour.
        /// </summary>
        internal static string Units_Kilometers_Hour
        {
            get
            {
                return ResourceManager.GetString("Units_Kilometers_Hour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kilopascal.
        /// </summary>
        internal static string Units_Kilopascal
        {
            get
            {
                return ResourceManager.GetString("Units_Kilopascal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Knots.
        /// </summary>
        internal static string Units_Knots
        {
            get
            {
                return ResourceManager.GetString("Units_Knots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        internal static string Units_Meters
        {
            get
            {
                return ResourceManager.GetString("Units_Meters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Meters per second.
        /// </summary>
        internal static string Units_Meters_Second
        {
            get
            {
                return ResourceManager.GetString("Units_Meters_Second", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        internal static string Units_Miles
        {
            get
            {
                return ResourceManager.GetString("Units_Miles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Miles per hour.
        /// </summary>
        internal static string Units_Miles_Hour
        {
            get
            {
                return ResourceManager.GetString("Units_Miles_Hour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Millibars.
        /// </summary>
        internal static string Units_Millibars
        {
            get
            {
                return ResourceManager.GetString("Units_Millibars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Milimeters.
        /// </summary>
        internal static string Units_Millimeters
        {
            get
            {
                return ResourceManager.GetString("Units_Millimeters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Torr (mmHg).
        /// </summary>
        internal static string Units_Torr
        {
            get
            {
                return ResourceManager.GetString("Units_Torr", resourceCulture);
            }
        }
    }
}
