//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xameteo.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xameteo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xameteo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xameteo.Resx.Xameteo", typeof(Xameteo).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faro Airport (FAO).
        /// </summary>
        internal static string airport_fao {
            get {
                return ResourceManager.GetString("airport_fao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cristiano Ronaldo International Airport (Funchal - FNC).
        /// </summary>
        internal static string airport_fnc {
            get {
                return ResourceManager.GetString("airport_fnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horta Airport (HOR).
        /// </summary>
        internal static string airport_hor {
            get {
                return ResourceManager.GetString("airport_hor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humberto Delgado Airport (Lisbon - LIS).
        /// </summary>
        internal static string airport_lis {
            get {
                return ResourceManager.GetString("airport_lis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francisco Sá Carneiro Airport (Porto - OPO).
        /// </summary>
        internal static string airport_opo {
            get {
                return ResourceManager.GetString("airport_opo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to João Paulo II Airport (Ponta Delgada - PDL).
        /// </summary>
        internal static string airport_pdl {
            get {
                return ResourceManager.GetString("airport_pdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porto Santo Airport (PXO).
        /// </summary>
        internal static string airport_pxo {
            get {
                return ResourceManager.GetString("airport_pxo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Santa Maria Airport (SMA).
        /// </summary>
        internal static string airport_sma {
            get {
                return ResourceManager.GetString("airport_sma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me!.
        /// </summary>
        internal static string buttonDefault {
            get {
                return ResourceManager.GetString("buttonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string condition_1000 {
            get {
                return ResourceManager.GetString("condition_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partly Cloudy.
        /// </summary>
        internal static string condition_1003 {
            get {
                return ResourceManager.GetString("condition_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        internal static string condition_1006 {
            get {
                return ResourceManager.GetString("condition_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string condition_1009 {
            get {
                return ResourceManager.GetString("condition_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mist.
        /// </summary>
        internal static string condition_1030 {
            get {
                return ResourceManager.GetString("condition_1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy rain nearby.
        /// </summary>
        internal static string condition_1063 {
            get {
                return ResourceManager.GetString("condition_1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy snow nearby.
        /// </summary>
        internal static string condition_1066 {
            get {
                return ResourceManager.GetString("condition_1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy sleet nearby.
        /// </summary>
        internal static string condition_1069 {
            get {
                return ResourceManager.GetString("condition_1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy freezing drizzle nearby.
        /// </summary>
        internal static string condition_1072 {
            get {
                return ResourceManager.GetString("condition_1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thundery outbreaks in nearby.
        /// </summary>
        internal static string condition_1087 {
            get {
                return ResourceManager.GetString("condition_1087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowing snow.
        /// </summary>
        internal static string condition_1114 {
            get {
                return ResourceManager.GetString("condition_1114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blizzard.
        /// </summary>
        internal static string condition_1117 {
            get {
                return ResourceManager.GetString("condition_1117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        internal static string condition_1135 {
            get {
                return ResourceManager.GetString("condition_1135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing fog.
        /// </summary>
        internal static string condition_1147 {
            get {
                return ResourceManager.GetString("condition_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light drizzle.
        /// </summary>
        internal static string condition_1150 {
            get {
                return ResourceManager.GetString("condition_1150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light drizzle.
        /// </summary>
        internal static string condition_1153 {
            get {
                return ResourceManager.GetString("condition_1153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing drizzle.
        /// </summary>
        internal static string condition_1168 {
            get {
                return ResourceManager.GetString("condition_1168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy freezing drizzle.
        /// </summary>
        internal static string condition_1171 {
            get {
                return ResourceManager.GetString("condition_1171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain.
        /// </summary>
        internal static string condition_1180 {
            get {
                return ResourceManager.GetString("condition_1180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain.
        /// </summary>
        internal static string condition_1183 {
            get {
                return ResourceManager.GetString("condition_1183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate rain at times.
        /// </summary>
        internal static string condition_1186 {
            get {
                return ResourceManager.GetString("condition_1186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate rain.
        /// </summary>
        internal static string condition_1189 {
            get {
                return ResourceManager.GetString("condition_1189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain at times.
        /// </summary>
        internal static string condition_1192 {
            get {
                return ResourceManager.GetString("condition_1192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy rain.
        /// </summary>
        internal static string condition_1195 {
            get {
                return ResourceManager.GetString("condition_1195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light freezing rain.
        /// </summary>
        internal static string condition_1198 {
            get {
                return ResourceManager.GetString("condition_1198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy freezing rain.
        /// </summary>
        internal static string condition_1201 {
            get {
                return ResourceManager.GetString("condition_1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light sleet.
        /// </summary>
        internal static string condition_1204 {
            get {
                return ResourceManager.GetString("condition_1204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet.
        /// </summary>
        internal static string condition_1207 {
            get {
                return ResourceManager.GetString("condition_1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow.
        /// </summary>
        internal static string condition_1210 {
            get {
                return ResourceManager.GetString("condition_1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light snow.
        /// </summary>
        internal static string condition_1213 {
            get {
                return ResourceManager.GetString("condition_1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy moderate snow.
        /// </summary>
        internal static string condition_1216 {
            get {
                return ResourceManager.GetString("condition_1216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate snow.
        /// </summary>
        internal static string condition_1219 {
            get {
                return ResourceManager.GetString("condition_1219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy heavy snow.
        /// </summary>
        internal static string condition_1222 {
            get {
                return ResourceManager.GetString("condition_1222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy snow.
        /// </summary>
        internal static string condition_1225 {
            get {
                return ResourceManager.GetString("condition_1225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice pellets.
        /// </summary>
        internal static string condition_1237 {
            get {
                return ResourceManager.GetString("condition_1237", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light rain shower.
        /// </summary>
        internal static string condition_1240 {
            get {
                return ResourceManager.GetString("condition_1240", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain shower.
        /// </summary>
        internal static string condition_1243 {
            get {
                return ResourceManager.GetString("condition_1243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torrential rain shower.
        /// </summary>
        internal static string condition_1246 {
            get {
                return ResourceManager.GetString("condition_1246", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light sleet showers.
        /// </summary>
        internal static string condition_1249 {
            get {
                return ResourceManager.GetString("condition_1249", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy sleet showers.
        /// </summary>
        internal static string condition_1252 {
            get {
                return ResourceManager.GetString("condition_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light snow showers.
        /// </summary>
        internal static string condition_1255 {
            get {
                return ResourceManager.GetString("condition_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow showers.
        /// </summary>
        internal static string condition_1258 {
            get {
                return ResourceManager.GetString("condition_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light showers of ice pellets.
        /// </summary>
        internal static string condition_1261 {
            get {
                return ResourceManager.GetString("condition_1261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy showers of ice pellets.
        /// </summary>
        internal static string condition_1264 {
            get {
                return ResourceManager.GetString("condition_1264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light rain in area with thunder.
        /// </summary>
        internal static string condition_1273 {
            get {
                return ResourceManager.GetString("condition_1273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy rain in area with thunder.
        /// </summary>
        internal static string condition_1276 {
            get {
                return ResourceManager.GetString("condition_1276", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patchy light snow in area with thunder.
        /// </summary>
        internal static string condition_1279 {
            get {
                return ResourceManager.GetString("condition_1279", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate or heavy snow in area with thunder.
        /// </summary>
        internal static string condition_1282 {
            get {
                return ResourceManager.GetString("condition_1282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atm.
        /// </summary>
        internal static string unit_Atmosphere {
            get {
                return ResourceManager.GetString("unit_Atmosphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ºC.
        /// </summary>
        internal static string unit_Celsius {
            get {
                return ResourceManager.GetString("unit_Celsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string unit_Centimeters {
            get {
                return ResourceManager.GetString("unit_Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ºF.
        /// </summary>
        internal static string unit_Fahrenheit {
            get {
                return ResourceManager.GetString("unit_Fahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string unit_Inches {
            get {
                return ResourceManager.GetString("unit_Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string unit_Kelvin {
            get {
                return ResourceManager.GetString("unit_Kelvin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string unit_Kilometers {
            get {
                return ResourceManager.GetString("unit_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kph.
        /// </summary>
        internal static string unit_KilometersPerHour {
            get {
                return ResourceManager.GetString("unit_KilometersPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        internal static string unit_Knots {
            get {
                return ResourceManager.GetString("unit_Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPa.
        /// </summary>
        internal static string unit_KPa {
            get {
                return ResourceManager.GetString("unit_KPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string unit_Meters {
            get {
                return ResourceManager.GetString("unit_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        internal static string unit_MetersPerSecond {
            get {
                return ResourceManager.GetString("unit_MetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        internal static string unit_Miles {
            get {
                return ResourceManager.GetString("unit_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string unit_MilesPerHour {
            get {
                return ResourceManager.GetString("unit_MilesPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milibars.
        /// </summary>
        internal static string unit_Milibars {
            get {
                return ResourceManager.GetString("unit_Milibars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string unit_Milimeters {
            get {
                return ResourceManager.GetString("unit_Milimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psi.
        /// </summary>
        internal static string unit_Psi {
            get {
                return ResourceManager.GetString("unit_Psi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torr.
        /// </summary>
        internal static string unit_Torr {
            get {
                return ResourceManager.GetString("unit_Torr", resourceCulture);
            }
        }
    }
}
